// Icon per stack item name, shared by the list and the globe.
import type { IconType } from "react-icons";
import {
  SiNextdotjs,
  SiReact,
  SiTypescript,
  SiAstro,
  SiVite,
  SiReactquery,
  SiSupabase,
  SiPostgresql,
  SiTailwindcss,
  SiVercel,
  SiStripe,
  SiShadcnui,
  SiRadixui,
  SiFramer,
  SiGreensock,
  SiReacthookform,
  SiNodedotjs,
  SiResend,
  SiPayloadcms,
  SiGraphql,
  SiOpenai,
  SiAnthropic,
  SiGooglechrome,
  SiGooglecalendar,
  SiGithub,
  SiDocker,
  SiCloudflare,
  SiGooglecloud,
  SiPosthog,
  SiSentry,
  SiBun,
  SiPython,
  SiJupyter,
  SiPandas,
  SiNumpy,
  SiScikitlearn,
  SiFirebase,
  SiRedis,
  SiMongodb,
  SiPrisma,
  SiJest,
  SiPostman,
  SiGo,
  SiRust,
  SiCplusplus,
  SiKubernetes,
  SiTerraform,
  SiCanva,
  SiZod,
  SiMdx,
} from "react-icons/si";
import { FaAws } from "react-icons/fa";
import {
  BarChart3,
  Bell,
  Command,
  Database,
  Globe,
  KeyRound,
  Mic,
  Moon,
  Film,
  Flame,
  Monitor,
  Plug,
  Satellite,
  Store,
  ScrollText,
  Search,
  TestTube,
  Workflow,
} from "lucide-react";

export const ICON_MAP: Record<string, IconType> = {
  "Next.js": SiNextdotjs,
  "React": SiReact,
  "TypeScript": SiTypescript,
  "Astro": SiAstro,
  "Vite": SiVite,
  "TanStack": SiReactquery,
  "Supabase": SiSupabase,
  "PostgreSQL": SiPostgresql,
  "Tailwind CSS": SiTailwindcss,
  "Vercel": SiVercel,
  "Stripe": SiStripe,
  "Shadcn UI": SiShadcnui,
  "Radix UI": SiRadixui,
  "Framer Motion": SiFramer,
  "GSAP": SiGreensock,
  "React Hook Form": SiReacthookform,
  "Node.js": SiNodedotjs,
  "Resend": SiResend,
  "Payload CMS": SiPayloadcms,
  "GraphQL": SiGraphql,
  "OpenAI API": SiOpenai,
  "Anthropic API": SiAnthropic,
  "Vercel AI SDK": SiVercel,
  "Chrome Extension APIs": SiGooglechrome,
  "Calendar APIs": SiGooglecalendar,
  "GitHub": SiGithub,
  "Docker": SiDocker,
  "Cloudflare": SiCloudflare,
  "AWS": FaAws,
  "GCP": SiGooglecloud,
  "PostHog": SiPosthog,
  "Sentry": SiSentry,
  "Bun": SiBun,
  "Python": SiPython,
  "Jupyter": SiJupyter,
  "pandas": SiPandas,
  "NumPy": SiNumpy,
  "scikit-learn": SiScikitlearn,
  "Firebase": SiFirebase,
  "Redis": SiRedis,
  "MongoDB": SiMongodb,
  "Prisma": SiPrisma,
  "Jest": SiJest,
  "Postman": SiPostman,
  "Go": SiGo,
  "Rust": SiRust,
  "C++": SiCplusplus,
  "Kubernetes": SiKubernetes,
  "Terraform": SiTerraform,
  "React Email": SiReact,
  "SQL": SiPostgresql,
  "Recharts": BarChart3,
  "cmdk": Command,
  "sonner": Bell,
  "Lenis": ScrollText,
  "Next Themes": Moon,
  "Neon": Database,
  "pgvector": Database,
  "Gladia API": Mic,
  "Exa API": Search,
  "OAuth": KeyRound,
  "WebSockets": Plug,
  "Playwright": TestTube,
  "Firecrawl": Flame,
  "Bright Data": Satellite,
  "Inngest": Workflow,
  "REST APIs": Globe,
  "Matplotlib": BarChart3,
  "Seaborn": BarChart3,
  "Zustand": Store,
  "Canva": SiCanva,
  "Premiere Pro": Film,
  "iMovie": Film,
  "Screen Studio": Monitor,
  "Zod": SiZod,
  "MDX": SiMdx,
};
